name: Build gothic3sdk

on: [push, pull_request]

jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 1

      - name: MSVC Development Environment
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: x86

      - name: Build with MSVC
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A Win32 -D CPM_SOURCE_CACHE=".\cpm-cache"
          cmake --build build --config Release -j

      - name: Build with MSVC (Ninja)
        run: |
          cmake -S . -B build-ninja -G Ninja -D CMAKE_BUILD_TYPE=Release -D CPM_SOURCE_CACHE=".\cpm-cache" -D CMAKE_EXPORT_COMPILE_COMMANDS=1
          cmake --build build-ninja

      - name: Build with ClangCl
        run: |
          cmake -S . -B build-clang -G "Visual Studio 17 2022" -A Win32 -T ClangCl -D CPM_SOURCE_CACHE=".\cpm-cache"
          cmake --build build-clang --config Release -j
